// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nliwgjfaqthjdpfmmmgo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5saXdnamZhcXRoamRwZm1tbWdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MzkxNTMsImV4cCI6MjA2NDIxNTE1M30.JBUdQRPt570J8RAgwSu7tGiGswy9ra5-v0YwQRZyzYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);